### PR TITLE
ci: test against ruby 2.7

### PR DESCRIPTION
**Pull request by mberlanda**
Run CI tests against ruby 2.7 as well

### CODE REVIEW

**Comment by mberlanda** [comment]
@amro it looks like the error handling is broken when the dependency to faraday is resolved to >= 1.0.0 :
e.g.

```
  1) Gibbon::APIRequest Faraday::Error::ClientError surfaces client request exceptions as a Gibbon::MailChimpError

     Failure/Error: let(:error_class) { Faraday::Error::ClientError }
     NameError:
       uninitialized constant Faraday::Error::ClientError
       Did you mean?  Faraday::ClientError

     Shared Example Group: "client error handling" called from ./spec/gibbon/api_request_spec.rb:66
     # ./spec/gibbon/api_request_spec.rb:64:in `block (3 levels) in <top (required)>'
     # ./spec/gibbon/api_request_spec.rb:14:in `block (3 levels) in <top (required)>'
```

**Comment by mberlanda** [comment]
Would it be suitable to follow the same versioning as faraday for this gem ? Otherwise, I would suggest to drop the support for faraday < 0.16 and bump a new version of the gem

**Comment by amro** [comment]
Thank you very much for helping. I prefer dropping old versions of faraday

**Comment by amro** [comment]
I’ll have to release a new version in a day or two — I’m traveling today

**Comment by amro** [comment]
Released

**Pull request merged**
