### PR TITLE
Fix chunks parsing when ending with ']'

### PR DESCRIPTION
**Pull request by okulik**
There is a very special case when data pulled from the MailChimp server using export API can cause Gibbon::MailChimpError errors. Follows a chunk that causes such exception:
```json
["some@email.com","Name","Last Name","Something something [1234]
```
Because ']' character is regarded as a special characters for the end of the line, that whole chunk will be mistakenly handed over to the JSON parser and will fail.

### CODE REVIEW

**Comment by amro** [comment]
I am sorry I missed this until now. I was heads down in November, though that's no excuse.

My understanding is API v2 will be shut down at the end of 2016 so I'm going to reject this PR.

**Comment by okulik** [comment]
Export API is not going away. api_v2 was the only place where I was able to find it, so I fixed it there.

**Comment by amro** [comment]
I see. I'll consider merging this then. In the mean time do you know MC has a new bulk API as part of v3?

Thanks,
Amro

**Comment by okulik** [comment]
They don't. They're keeping export API the way it is because it has rather special purpose. Perhaps you might keep export code in api_v3 branch as well?

**Comment by amro** [comment]
Yes. I'm thinking adding export support to v3/master is the way to go. I'd rather not release an old version of the gem that mainly targets the old API that is going away shortly.

There is indeed a bulk API in v3, but as you say it's not quite the same as the export API. It's not a streaming/chunked API.

Thanks,
Amro

**Comment by amro** [comment]
@okulik I've added support (in master) for Export API. It's not well tested and I've not yet written unit tests for it. Could you please create a PR w/ your fix against master? After this and after adding tests I will release Gibbon 3.0.0.

**Comment by amro** [comment]
I went ahead and did it. I credited you with the fix in the commit message.

**Pull request closed without merging**
