### PR TITLE
Allow for custom adapter using Faraday

### PR DESCRIPTION
**Pull request by yez**
@amro 

Faraday supports many different adapters, this enables the APIRequest
  to be initialized with a custom adapter.

In the same way that the api_key, api_endpoint, and timeout variables
  are passed through the builder, the faraday_adapter can be passed
  through as well.

### CODE REVIEW

**Comment by amro** [comment]
Thanks @yez! Honest question here: Is this something people want to do and why? i.e. Is some particular adapter faster or better than another in some way?

I ask because it seems to leak a bit about the internals of Gibbon in the top level API and I'm not sure that's good. For example, I could choose to move Gibbon to another http lib (or just net::http if I wanted to deal with a little pain in exchange for one less dependency). That's really an implementation detail that I've tried to abstract away in the API.

**Comment by yez** [comment]
One of the great benefits of using Faraday is that if you have to use external HTTP services and need to use different backends for a particular use case, it lets you.

For instance, if you have a process that needs to make multiple HTTP requests at the same time, you can use the [`:em_synchrony`](https://github.com/igrigorik/em-synchrony) backend to help parallelize* your requests. If a piece of your application needs to use it, others will as well. Think of the case when you have multiple HTTP APIs to call (like a user service, search service and email service) for one specific job.

(*you can not actually parallelize with MRI but `:em_synchrony` takes care of fiber yielding and continuing for you)

In terms of leaking, I'm not sure it does anything more harmful than the same ability to set the timeout flag during initialization, or at least it seems that way to me.

**Comment by yez** [comment]
I think the gist of what I am trying to say is that yes, this couples the Gibbon library more closely to Faraday and if you choose to move away from it then it will break people's code which used that coupling.

I think the trade off is worth it though, since Faraday's point is to not need to move away from it (as it has a replace-able backend), I'd wager that this trade is fair to make to at least enable users a different Faraday backend at all.

**Comment by amro** [comment]
I understand. I'm noodling on that. I think I agree but give me a little more time. :)

Thanks,
Amro

**Comment by amro** [comment]
Thanks for contributing, @yez. I'll release this and a prior contribution in the next day or two.

**Comment by yez** [comment]
Glad you found it useful!

**Pull request merged**
