### PR TITLE
Updated readme.

### PR DESCRIPTION
**Pull request by dwkns**
I've updated the readme to make it clearer how Gibbon works with respect to calling resources.

Also have given an example of how to use file-manager/files resource. The underscore verses dash thing in resource names wasn't very clear.

### CODE REVIEW

**Comment by dwkns** [comment]
Updated with some clearer examples of how to use the file manager.

**Comment by amro** [comment]
Thanks. I'm on vacation. Will look at this afterward.

Thanks,
Amro

**Comment by amro** [comment]
I'm not going to merge this PR. There's a note in the README about hyphens and underscores:

    MailChimp's resource documentation is a list of available resources. Substitute an underscore if a resource name contains a hyphen.

The README is not intended to replace MailChimp's documentation but rather to explain how to use Gibbon. It's important that folks reference MailChimp's docs directly when using Gibbon in case they're updated.

I would accept a PR to make the note I mentioned above more prominent. I can do that myself, if you think it would be helpful.

**Comment by dwkns** [comment]
I understand what you're getting at. The issue I've had is it's not always obvious how to translate the API calls into Gibbon calls. And figuring things out (especially for people without lots of experience is hard).

I do think that several things need to be clearer but also understand that the README is not necessarily the place for tons of examples. 

How about I create some Wiki Pages for examples and then do a new PR for the README concentrating on how to use Gibbon and linking to the Wiki for more info?

**Comment by amro** [comment]
That sounds good. To be clear, the changes to the README would focus on how to map API calls from URL/REST to Gibbon's syntax. Is that correct? For instance, you might explain then show a few short examples of paths like

    /lists/{id}/members/{member_id}

then show what it would look like when converted to Gibbon's syntax?

Thanks for contributing. 💯

**Comment by dwkns** [comment]
Yep, that's exactly what I was thinking. Then in the Wiki we can go into more detailed examples and just link to them from the README. I'll try and get something done next week.

**Pull request closed without merging**
